### ISSUE TITLE
[wasmc++] use of undeclared identifier 'rand'

### ISSUE THREAD

**Issue by heddendorp** [wasienv/wasienv#19]
I'm aware that this might not be the kind of issue for here, but extensive googling has not given me any results.
I'm trying to compile 
```c
void random_shuffle(unsigned int *list, int32_t N)
{
    for (int32_t i=0; i<N-1; ++i) {
        int32_t swap_ix = i + rand() % (N-i);
        unsigned int tmp = list[swap_ix];
        list[swap_ix] = list[i];
        list[i] = tmp;
    }
}
```
By using `wasmc++ -Os -Wl,--strip-all -nostdlib wasm/test.cpp -o wasm/test.cpp.wasm` which gives me:
```
wasm/test.cpp:14:31: error: use of undeclared identifier 'rand'
        int32_t swap_ix = i + rand() % (N-i);
```

I'd be glad to be pointed in the right direction to find out how to get a random number.

**Comment by MarkMcCaskey** [comment]
It looks like the `-nostdlib` is probably the issue here!

In C I believe `rand` is in `stdlib.h`.  If your goal is to compile to WASI, then you'll want to use the stdlib to have these calls translated into their WASI equivalents.

As-is, `rand` is an undefined symbol that is never resolved during compilation and ends up as a top-level import.  If the Wasm environment you want to execute this has a `rand` import exposed to its Wasm modules, then this Wasm binary can work, but otherwise it won't work.

Feel free to follow up if you need more help, but it comes down to: you need to pick an ABI like Emscripten or WASI and compile to that, or you need to create a host environment with the imports that your program uses.  It depends entirely on what you're using Wasm for!
